version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 16...
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
      - apt install -y nodejs

#      - echo Installing NPM...
#      - apt install -y npm

  pre_build:
    commands:

      - echo veryfing cache...
      - npm cache verify

      - echo Installing dependencies...
      - npm install
  build:
    commands:
#      - echo Testing...
#      - npm test
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build 
